### ISSUE TITLE
Why is the maximum minimum value of the owd value constant (minimum is 60, maximum is 142)

### ISSUE THREAD

**Issue by wlwl1011** [SoonyangZhang/quic-on-ns3#12]
Hello! 
I have a question for you!
We are continuously conducting experiments using TCP and QUIC codes that can be experimented in the ns3 environment posted by Soonyang Zhang, and we found a singularity in the one-way delay value of QUIC.
No matter what the error rate was in the network environment, the maximum and minimum values of the one-way delay values were always constant, no matter what the congestion control algorithm was!
(The graph below shows the experiment using the ns3 TCP and QUIC codes posted by Soonyang Zhang, and the maximum minimum value is plotted using Python matplotlib!)

[delete]

Curious as to why these results are derived, we looked at the QUIC for a specific function to adjust the one-way delay value, but found no particular singularity..
Did Soonyang Zhang set up a separate code regarding the maximum value of the one-way delay?!
If you know anything about this, please reply!
Thank you all the time :)

**Comment by SoonyangZhang** [comment]
The minimum delay is the queue is its lowest level. When the buffer is fully occupied, the largest delay is observerd. IN TCP，I think the delay is rtt, the packet will be transmited when loss detected. And the rtt is large if packet is retrans. Each packet has a unique seq number in quic, even the trans packet has a new seq. The delay estimation in quic is more accurate. And the delay info is one way delay in quic-on-ns3 is got by insert Ns3QuicTag in Packet obj. And Linus tell us: just read the source code. Hope this helps.

---Original---
From: ***@***.***&gt;
Date: Sun, Aug 27, 2023 13:09 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [SoonyangZhang/quic-on-ns3] Why is the maximum minimum value of theowd value constant (Issue #12)




 
Hello!
 I have a question for you!
 We are continuously conducting experiments using TCP and QUIC codes that can be experimented in the ns3 environment posted by Soonyang Zhang, and we found a singularity in the one-way delay value of QUIC.
 No matter what the error rate was in the network environment, the maximum and minimum values of the one-way delay values were always constant, no matter what the congestion control algorithm was!
 (The graph below shows the experiment using the ns3 TCP and QUIC codes posted by Soonyang Zhang, and the maximum minimum value is plotted using Python matplotlib!)
 

 
Curious as to why these results are derived, we looked at the QUIC for a specific function to adjust the one-way delay value, but found no particular singularity..
 Did Soonyang Zhang set up a separate code regarding the maximum value of the one-way delay?!
 If you know anything about this, please reply!
 Thank you all the time :)

**Comment by wlwl1011** [comment]
Thanks a lot ! 😀😀
