### ISSUE TITLE
Linking Error 

### ISSUE THREAD

**Issue by Jazkiel** [SoonyangZhang/quic-on-ns3#13]
I followed all the steps mentioned here but get this error while trying to run quic-main.cc  fatal error: ns3/quic-module.h: No such file or directory
. Can you please help here?

**Comment by SoonyangZhang** [comment]
put the quic module(https://github.com/SoonyangZhang/quic-on-ns3/tree/main/quic ) under src and build. ns3 will auto generate ns3/quic-module.h. The put the main file (https://github.com/SoonyangZhang/quic-on-ns3/tree/main/scratch) to scratch folder in ns3 and run "./waf build" again.

Jon Snow, you know nothing about ns3!

**Comment by Jazkiel** [comment]
Yes, thank you. I realised I was doing this in ns3.40, I changed to ns 3.33, it does start including it but now I am unable to link the lquiche_shared. I can echo the LD_LIBRARY_PATH and it shows correct value,I manually made the symbolic link to libquiche_shared.so  but still ld lquiche_shared --verbose does not find the link, any thoughts?

**Comment by SoonyangZhang** [comment]
Download quiche in release page and build it. Readme tells you tips.



---Original---
From: "Jashanjot ***@***.***&gt;
Date: Tue, Oct 24, 2023 22:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [SoonyangZhang/quic-on-ns3] Linking Error  (Issue #13)




 
Yes, thank you. I realised I was doing this in ns3.40, I changed to ns 3.33, it does start including it but now I am unable to link the lquiche_shared. I can echo the LD_LIBRARY_PATH and it shows correct value,I manually made the symbolic link to libquiche_shared.so  but still ld lquiche_shared --verbose does not find the link, any thoughts?

**Comment by Jazkiel** [comment]
I tried that too, It had some string overflow errors so I made the shared library changes in this repo https://github.com/bilibili/quiche and built it, I am able to generate the libquiche_shared.so in my build folder, just the linking does not work for me

**Comment by Jazkiel** [comment]
ld: mode elf_x86_64
attempt to open /usr/local/lib/x86_64-linux-gnu/libquiche_shared.so failed
attempt to open /usr/local/lib/x86_64-linux-gnu/libquiche_shared.a failed
attempt to open /lib/x86_64-linux-gnu/libquiche_shared.so failed
attempt to open /lib/x86_64-linux-gnu/libquiche_shared.a failed
attempt to open /usr/lib/x86_64-linux-gnu/libquiche_shared.so failed
attempt to open /usr/lib/x86_64-linux-gnu/libquiche_shared.a failed
attempt to open /usr/lib/x86_64-linux-gnu64/libquiche_shared.so failed
attempt to open /usr/lib/x86_64-linux-gnu64/libquiche_shared.a failed
attempt to open /usr/local/lib64/libquiche_shared.so failed
attempt to open /usr/local/lib64/libquiche_shared.a failed
attempt to open /lib64/libquiche_shared.so failed
attempt to open /lib64/libquiche_shared.a failed
attempt to open /usr/lib64/libquiche_shared.so failed
attempt to open /usr/lib64/libquiche_shared.a failed
attempt to open /usr/local/lib/libquiche_shared.so failed
attempt to open /usr/local/lib/libquiche_shared.a failed
attempt to open /lib/libquiche_shared.so failed
attempt to open /lib/libquiche_shared.a failed
attempt to open /usr/lib/libquiche_shared.so failed
attempt to open /usr/lib/libquiche_shared.a failed
attempt to open /usr/x86_64-linux-gnu/lib64/libquiche_shared.so failed
attempt to open /usr/x86_64-linux-gnu/lib64/libquiche_shared.a failed
attempt to open /usr/x86_64-linux-gnu/lib/libquiche_shared.so failed
attempt to open /usr/x86_64-linux-gnu/lib/libquiche_shared.a failed
ld: cannot find -lquiche_shared: No such file or directory
attempt to open /usr/local/lib/x86_64-linux-gnu/libquiche_shared.so failed
attempt to open /usr/local/lib/x86_64-linux-gnu/quiche_shared.a failed
attempt to open /lib/x86_64-linux-gnu/libquiche_shared.so failed
attempt to open /lib/x86_64-linux-gnu/quiche_shared.a failed
attempt to open /usr/lib/x86_64-linux-gnu/libquiche_shared.so failed
attempt to open /usr/lib/x86_64-linux-gnu/quiche_shared.a failed
attempt to open /usr/lib/x86_64-linux-gnu64/libquiche_shared.so failed
attempt to open /usr/lib/x86_64-linux-gnu64/quiche_shared.a failed
attempt to open /usr/local/lib64/libquiche_shared.so failed
attempt to open /usr/local/lib64/quiche_shared.a failed
attempt to open /lib64/libquiche_shared.so failed
attempt to open /lib64/quiche_shared.a failed
attempt to open /usr/lib64/libquiche_shared.so failed
attempt to open /usr/lib64/quiche_shared.a failed
attempt to open /usr/local/lib/libquiche_shared.so failed
attempt to open /usr/local/lib/quiche_shared.a failed
attempt to open /lib/libquiche_shared.so failed
attempt to open /lib/quiche_shared.a failed
attempt to open /usr/lib/libquiche_shared.so failed
attempt to open /usr/lib/quiche_shared.a failed
attempt to open /usr/x86_64-linux-gnu/lib64/libquiche_shared.so failed
attempt to open /usr/x86_64-linux-gnu/lib64/quiche_shared.a failed
attempt to open /usr/x86_64-linux-gnu/lib/libquiche_shared.so failed
attempt to open /usr/x86_64-linux-gnu/lib/quiche_shared.a failed

**Comment by SoonyangZhang** [comment]
https://github.com/SoonyangZhang/quic-on-ns3/releases/tag/quiche  
download it and build  it.   
Then following each tips on ReadMe. Ok? 
You are not the first to build this repo. There is no such error for others.

**Comment by Jazkiel** [comment]
The issue btw is with ubuntu 22.04 itself, works perfectly on ubuntu 20.04

**Comment by SoonyangZhang** [comment]
glad to hear that.
