### ISSUE TITLE
quic over lte

### ISSUE THREAD

**Issue by tamersh98** [SoonyangZhang/quic-on-ns3#16]
im trying to build simple quic over lte example in ns3.37 , my topology looks like this 
|                        |                                                   |      |
| quic - server   | --->| PGW| -- |SGW|--|ENB| --> | UE | 
|                        |                                                   |      |
 
my code is calculating the throughput by changing the distance between UE and ENB nodes , but i think the same amount of bytes keep sending everytime i change the distance the throughput is not affected , i used bulksendHelper.

can you give me an example code how i should define this topology ? or anything similar?

**Comment by SoonyangZhang** [comment]
1 sorry, I am not familiar with ns3 part on wireless simulation.
2 bulksendHelper send data over TCP （https://github.com/nsnam/ns-3-dev-git/blob/ns-3.37/src/applications/model/bulk-send-application.cc#L144.
3 So，it not the topology to blame.
