### ISSUE TITLE
A error when copy the folder quic to src and build：“找不到 -lquiche_shared collect2: error: ld returned 1 exit status”

### ISSUE THREAD

**Issue by 404keke** [SoonyangZhang/quic-on-ns3#2]
已经严格按照大佬的步骤去设置了，把quic移动到src目录后编译会报错“找不到 -lquiche_shared collect2: error: ld returned 1 exit status”，还望大佬指正。

**Comment by SoonyangZhang** [comment]
download  quiche code (https://pan.baidu.com/s/1F4LTfXn5KHR1LcNa5yXkkA) and build it (https://github.com/SoonyangZhang/quic-on-ns3#build-quiche).
