### ISSUE TITLE
安装quic库过程中出现error: no matching function for call to ‘quic::QuicTime::QuicTime()’等错误

### ISSUE THREAD

**Issue by zzuchen** [SoonyangZhang/quic-on-ns3#3]
![ZZ0`P _~8FPF0I)KTG LR%O](https://user-images.githubusercontent.com/58057154/159275774-ac5f80ba-1aa0-4126-bd64-421837446fe3.png)
您好，在安装quic库的过程中出现上述错误该怎么解决啊？

**Comment by SoonyangZhang** [comment]
build quiche first (https://pan.baidu.com/s/1F4LTfXn5KHR1LcNa5yXkkA) and set the environmental virables(https://github.com/SoonyangZhang/quic-on-ns3#add-environmental-variable).
