### ISSUE TITLE
Is there any way to control how much total number of transmitted bytes the server sends to the client?

### ISSUE THREAD

**Issue by wlwl1011** [SoonyangZhang/quic-on-ns3#6]
Hi there!
I'm writing this after looking at your code again!

In the TCP code, there is a code called totalTxBytes, I think TxByte means total number of transmitted bytes , is it right??
![Untitled](https://user-images.githubusercontent.com/62577565/226523935-736e715c-fa9c-468e-8d1f-d4b6b18e6dc7.jpg)

So, just as we can set the total number of transmitted bytes in TCP, I thought I'd do the same in QUIC.

By any chance, what is the total number of transmitted bytes the server sends to the client set to? Can I check it out, and can it be adjusted arbitrarily? I'd like to try sending very little and very much data! 

![Untitled](https://user-images.githubusercontent.com/62577565/226524991-faf8a243-2cb0-4aeb-a40b-54fe12a384a5.jpg)
![Untitled](https://user-images.githubusercontent.com/62577565/226525036-722fbbb6-1e75-45e5-9b92-ebdc01fcea80.jpg)

But no matter how much I poked around in the code, I couldn't find the total amount of data the server sends to the client.... 🥲🥲🥲

Does NS3 just set the default value by itself and run the simulation?
Or is it just that when I configure the topology, if I increase the bps, the server sends more data for the time set in the simulation, and if I decrease the bps, the server sends less data?

![Untitled](https://user-images.githubusercontent.com/62577565/226525985-de8f13dd-8b1f-416f-b18a-f7ec13ff16a7.jpg)

Or, do I create a QUIC of type HELLO_UNIDI and set it up???  

![Untitled](https://user-images.githubusercontent.com/62577565/226529500-aba01772-933a-4ac9-a225-41aa72c26e60.jpg)

I apologize for bothering you every time.
Thanks for reading!

**Comment by SoonyangZhang** [comment]
I  test the performance for congestio cotrol. the server only receive packets. If you  are familar wit  quic protocol, you can do whatevet you want.

**Comment by wlwl1011** [comment]
Yep! Sorry to keep asking, have a restful night :)
