### ISSUE TITLE
How to print cwnd

### ISSUE THREAD

**Issue by wlwl1011** [SoonyangZhang/quic-on-ns3#7]
Hello !
I'm looking foward print cwnd.
So I set the flag just like that!

![Untitled 2](https://user-images.githubusercontent.com/62577565/227430028-2845226d-e0d1-49e9-94a4-2514d599a831.jpg)

But, When I open the cwnd file , The file is empty!  Nothing was printed!

I'm getting goodput, sendrate, inflight, loss rate, etc. to output correctly, but only cwnd is not outputting! Is there any code I need to add?

**Comment by wlwl1011** [comment]
I added code, and It's working !!
haha ^^

```
if (client_log_flag & E_QC_CWND)
            {
                client_app->SetCwndTraceFun(MakeCallback(&Ns3QuicClientTrace::OnCwnd, trace));
            }
```

Thanks all days :)

**Comment by SoonyangZhang** [comment]
```
 client_app->SetInFlightTraceFun  
```

for  BBR algorithm，cwnd is meaningless. And inflight will count how many packets on the pipe.

**Comment by wlwl1011** [comment]
Thank you !!!!!!!!!!!!!
