### ISSUE TITLE
How to add some other imformation into the packet, for example: ack_delay?

### ISSUE THREAD

**Issue by rsr623** [SoonyangZhang/quic-on-ns3#9]
ack_delay has been implemented in Google Quiche, and can be found here: https://github.com/google/quiche/search?q=ack_delay
but I can not find this value in this quic-on-ns3, so I want to implement it.
ack_delay represents a deliberate delay in sending the ACK by the receiver, and it will be used in computing RTT samples. So if this has been implemented? Or what files should I modify to achieve this feature?
Thanks for your help!

**Comment by SoonyangZhang** [comment]
https://github.com/bilibili/quiche/blob/300138e635f64e9e8d0cc98a907bda264438bbf7/gquiche/quic/core/quic_stream.h#L338
```
  // Called when data [offset, offset + data_length) is acked. |fin_acked|
  // indicates whether the fin is acked. Returns true and updates
  // |newly_acked_length| if any new stream data (including fin) gets acked.
  virtual bool OnStreamFrameAcked(QuicStreamOffset offset,
                                  QuicByteCount data_length, bool fin_acked,
                                  QuicTime::Delta ack_delay_time,
                                  QuicTime receive_timestamp,
                                  QuicByteCount* newly_acked_length);
```

**Comment by SoonyangZhang** [comment]
Inherite the OnStreamFrameAcked  in Ns3TransportStream.
https://github.com/SoonyangZhang/quic-on-ns3/blob/main/quic/model/ns3-transport-stream.h

**Comment by rsr623** [comment]
Thank you for your response, but I am a novice using NS3, and I don't quite understand the meaning of enabling the OnStreamFrameAcked function you mentioned.  
I think there are many places that need to be modified here, such as how to retrieve information in ACK, whether the protocol stack in user space needs to be changed to accommodate the addition of a new attribute representing ACK delay, and even determining the maximum value of ACK delay during the handshake negotiation.  
Can all these features be implemented simply by enabling the OnStreamFrameAcked function? And will this not interfere with other existing normal functions? Thank you once again for your help!

**Comment by SoonyangZhang** [comment]
ack is support by quiche library.  This model depends on google  quiche library. you want to extact such info or intend to add some delay on ack packets ?

**Comment by rsr623** [comment]
In other words, since both the Client and Server are using the gQUIC library now, they have already generated the ACK_delay data according to the requirements, and included it in the ACK, so there's no need for any adjustments? All we need to do is to place this function OnStreamFrameAcked as it is into OnStreamFrameAcked, and the correct functionality can be achieved? 

Cool! I mistakenly thought all features in NS3 had to be implemented by oneself, instead of relying on external libraries like this.

I understand this might seem like a silly question to you, but I still appreciate your patience. I will give it a try to see if it works properly. Thanks again!

**Comment by rsr623** [comment]
> 

Both are desired: I hope to adjust the ack_delay added at the receiver, and correctly extract the ack_delay at the sender.

**Comment by rsr623** [comment]
Thanks! I know how to achieve it, I mistakenly thought all features in NS3 had to be implemented by oneself, instead of relying on external libraries like this.

I understand this might seem like a silly question to you, but I still appreciate your patience. I will give it a try to see if it works properly. Thanks again!
